// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/sentinel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_PING  JobType = 0
	JobType_SHELL JobType = 1
	JobType_SCAN  JobType = 2
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "PING",
		1: "SHELL",
		2: "SCAN",
	}
	JobType_value = map[string]int32{
		"PING":  0,
		"SHELL": 1,
		"SCAN":  2,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_sentinel_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_api_proto_sentinel_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_api_proto_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_api_proto_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemUsage      float64                `protobuf:"fixed64,4,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_api_proto_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatReq) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatReq) GetMemUsage() float64 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type          JobType                `protobuf:"varint,2,opt,name=type,proto3,enum=sentinel.JobType" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_api_proto_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_PING
}

func (x *Job) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ReportJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobReq) Reset() {
	*x = ReportJobReq{}
	mi := &file_api_proto_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobReq) ProtoMessage() {}

func (x *ReportJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobReq.ProtoReflect.Descriptor instead.
func (*ReportJobReq) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *ReportJobReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportJobReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportJobReq) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ReportJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportJobResp) Reset() {
	*x = ReportJobResp{}
	mi := &file_api_proto_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobResp) ProtoMessage() {}

func (x *ReportJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobResp.ProtoReflect.Descriptor instead.
func (*ReportJobResp) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *ReportJobResp) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type HeartbeatResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigOutdated bool                   `protobuf:"varint,1,opt,name=config_outdated,json=configOutdated,proto3" json:"config_outdated,omitempty"`
	Job            *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_api_proto_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResp) GetConfigOutdated() bool {
	if x != nil {
		return x.ConfigOutdated
	}
	return false
}

func (x *HeartbeatResp) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_api_proto_sentinel_proto protoreflect.FileDescriptor

const file_api_proto_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/sentinel.proto\x12\bsentinel\"M\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"C\n" +
	"\fRegisterResp\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x81\x01\n" +
	"\fHeartbeatReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tmem_usage\x18\x04 \x01(\x01R\bmemUsage\"]\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.sentinel.JobTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"p\n" +
	"\fReportJobReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\"+\n" +
	"\rReportJobResp\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"Y\n" +
	"\rHeartbeatResp\x12'\n" +
	"\x0fconfig_outdated\x18\x01 \x01(\bR\x0econfigOutdated\x12\x1f\n" +
	"\x03job\x18\x02 \x01(\v2\r.sentinel.JobR\x03job*(\n" +
	"\aJobType\x12\b\n" +
	"\x04PING\x10\x00\x12\t\n" +
	"\x05SHELL\x10\x01\x12\b\n" +
	"\x04SCAN\x10\x022\xd2\x01\n" +
	"\x0fSentinelService\x129\n" +
	"\bRegister\x12\x15.sentinel.RegisterReq\x1a\x16.sentinel.RegisterResp\x12@\n" +
	"\tHeartbeat\x12\x16.sentinel.HeartbeatReq\x1a\x17.sentinel.HeartbeatResp(\x010\x01\x12B\n" +
	"\x0fReportJobStatus\x12\x16.sentinel.ReportJobReq\x1a\x17.sentinel.ReportJobRespB\aZ\x05./;pbb\x06proto3"

var (
	file_api_proto_sentinel_proto_rawDescOnce sync.Once
	file_api_proto_sentinel_proto_rawDescData []byte
)

func file_api_proto_sentinel_proto_rawDescGZIP() []byte {
	file_api_proto_sentinel_proto_rawDescOnce.Do(func() {
		file_api_proto_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sentinel_proto_rawDesc), len(file_api_proto_sentinel_proto_rawDesc)))
	})
	return file_api_proto_sentinel_proto_rawDescData
}

var file_api_proto_sentinel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_sentinel_proto_goTypes = []any{
	(JobType)(0),          // 0: sentinel.JobType
	(*RegisterReq)(nil),   // 1: sentinel.RegisterReq
	(*RegisterResp)(nil),  // 2: sentinel.RegisterResp
	(*HeartbeatReq)(nil),  // 3: sentinel.HeartbeatReq
	(*Job)(nil),           // 4: sentinel.Job
	(*ReportJobReq)(nil),  // 5: sentinel.ReportJobReq
	(*ReportJobResp)(nil), // 6: sentinel.ReportJobResp
	(*HeartbeatResp)(nil), // 7: sentinel.HeartbeatResp
}
var file_api_proto_sentinel_proto_depIdxs = []int32{
	0, // 0: sentinel.Job.type:type_name -> sentinel.JobType
	4, // 1: sentinel.HeartbeatResp.job:type_name -> sentinel.Job
	1, // 2: sentinel.SentinelService.Register:input_type -> sentinel.RegisterReq
	3, // 3: sentinel.SentinelService.Heartbeat:input_type -> sentinel.HeartbeatReq
	5, // 4: sentinel.SentinelService.ReportJobStatus:input_type -> sentinel.ReportJobReq
	2, // 5: sentinel.SentinelService.Register:output_type -> sentinel.RegisterResp
	7, // 6: sentinel.SentinelService.Heartbeat:output_type -> sentinel.HeartbeatResp
	6, // 7: sentinel.SentinelService.ReportJobStatus:output_type -> sentinel.ReportJobResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_sentinel_proto_init() }
func file_api_proto_sentinel_proto_init() {
	if File_api_proto_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sentinel_proto_rawDesc), len(file_api_proto_sentinel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sentinel_proto_goTypes,
		DependencyIndexes: file_api_proto_sentinel_proto_depIdxs,
		EnumInfos:         file_api_proto_sentinel_proto_enumTypes,
		MessageInfos:      file_api_proto_sentinel_proto_msgTypes,
	}.Build()
	File_api_proto_sentinel_proto = out.File
	file_api_proto_sentinel_proto_goTypes = nil
	file_api_proto_sentinel_proto_depIdxs = nil
}
